name: Push to Main

on:
  push:
    branches:
      - main

jobs:
  push-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Reset to specific commit
        run: |
          git reset --hard 90c073e51729f875e21ee1f41f694dee5fe12e18
          git push --force origin main
